language: node_js
node_js:
- '5.5'
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - nick@callmenick.com
    on_success: change
    on_failure: always
install:
- npm install
- if [ "$TRAVIS_BRANCH" == "master" ] ; then npm run build:production ; fi
deploy:
  provider: heroku
  strategy: api
  skip_cleanup: true
  api_key:
    secure: kNOKqJpAlRXo/mROiSJMnZw9JmiCYvqZPB4aM6HMsJrJtuwhczmqWk5LYD2MXBg2WvFgeiI3XDjH0F7RFeyiXBywOS64sfqtgVqVn3iQObFg/XWAt9HNevoi4SUDF5pdMPfAA+JLbHBQMCXLmkKzHUJmxiaEMC5h56bv8C15bsrM11UqcnNnfJrK9t1KbwKRxseJYh4y8iFfl9HTg9FRboKwzhhmlYpsrvS8EDJpXHwbCwfD9fst34xnIgE/zluc8xRCf5UyJXBvDubWjQMNHldjyk5tMGz52HknZ0HdWMxOqgMRkqztDsXDDLCTWLv8+RTKTEh2hl9dvrbYJUI7Ut2xEX6ljOdbOT3Hy6cpjvFdUevyP6332xp8kjf5fDqx/sa9bsbwWEd/u2FjNmnKZOfYBMBiMVvjDXESlbiUkAHAR0tImJx1Pfwk/lt3116y7WwvQUkvCQu1zaaz3x9i8jWEEdB0qYr6tUClSS7FMl6JxG9lSnFuB0Ls8XvwjFCIxaASnmszH47wyYBFakkbYB+zpwVDIAtYXxklubdFmHUHSg2aiE5KceftO1FdL+SU8QWmseT6yjp8FeolQU5CN/A5HNboGRbUpMj5C212/NoJ9thXWAdOEAVQeMThNoSKUfJaTR5QsOuFGaEQ3Wl87EMab/Dw1Pk6kfbyVL89Kbc=
  app:
    master: fruitz
